---
  friday_url:
    description: "Friday Jenkins URL"
    type: "string"
    required: true
  friday_user:
    description: "Friday Jenkins username"
    type: "string"
    required: true
  friday_password:
    description: "Friday Jenkins password (user API token)"
    type: "string"
    required: true
    secret: true
