---
- name: Install st2
  hosts: all
  environment: "{{ st2_proxy_env | default({}) }}"
  vars:
    st2_auth_password: admin
    hubot_slack_token: xoxb-3831804017712-3810465671652-iZmY1D74iB7Ypmjia12ALudp
    helper_slack_token: xoxb-3831804017712-3810465671652-iZmY1D74iB7Ypmjia12ALudp
  roles:
    - StackStorm.mongodb
    - StackStorm.rabbitmq
    - StackStorm.redis
    - StackStorm.st2repo
    - StackStorm.st2
    - StackStorm.nginx
    - StackStorm.st2web
    - StackStorm.nodejs
    - StackStorm.st2chatops
    - StackStorm.st2smoketests
    - test.st2_configure
    - test.st2_deploy
